services:
  cupload:
    # TAG will be provided by environment variable during deployment
    image: ${TAG}
    container_name: cupload
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/cupload/uploads:/uploads
