services:
  cupload:
    # TAG will be provided by environment variable during deployment
    image: ${TAG}
    container_name: cupload
    restart: unless-stopped
    environment:
      - UPLOAD_FOLDER=/uploads
    # Internal usage only
    volumes:
      - /opt/cupload/uploads:/uploads

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /opt/qurl_data/certbot/conf:/etc/letsencrypt
      - /opt/qurl_data/certbot/www:/var/www/certbot
    depends_on:
      - cupload

  certbot:
    image: certbot/certbot
    volumes:
      - /opt/qurl_data/certbot/conf:/etc/letsencrypt
      - /opt/qurl_data/certbot/www:/var/www/certbot

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    # Enable env var expansion and point to custom config path to force non-default usage
    command: -config.file=/etc/promtail/docker-config.yml -config.expand-env=true
    volumes:
      - ./observability/promtail.yml:/etc/promtail/docker-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOKI_USER=${LOKI_USER}
      - LOKI_PASSWORD=${LOKI_PASSWORD}
      - LOKI_HOST=${LOKI_HOST}
    restart: unless-stopped
